# ===================================================================
#                      测试环境配置 (test)
# ===================================================================
server:
  port: 8082 # 测试服务器使用 8082 端口

logging:
  level:
    com.momentum: info

# 测试环境数据库配置 (示例)
# spring:
#   datasource:
#     url: jdbc:mysql://test-db-host:3306/momentum_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#     username: test_user
#     password: test_password
