# ===================================================================
#                      主配置文件 (通用配置)
# ===================================================================
spring:
  # 应用名称，所有环境都一样
  application:
    name: momentum-suite

  # **核心：指定默认激活的环境**
  # 在开发时，我们通常默认激活 dev 环境。
  profiles:
    active: dev

  # Jackson JSON 处理配置，通常是通用的
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization:
      fail-on-unknown-properties: false

# 服务器通用配置
server:
  servlet:
    context-path: /momentum-suite
  tomcat:
    uri-encoding: UTF-8
  shutdown: graceful

# Actuator 监控端点配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
