# ===================================================================
#                      生产环境配置 (prod)
# ===================================================================
server:
  port: 8080 # 生产环境通常使用 80 或 8080 端口

logging:
  level:
    com.momentum: warn # 生产环境日志级别应为 WARN 或 ERROR，避免性能损耗

# 生产环境数据库配置 (示例)
# spring:
#   datasource:
#     url: jdbc:mysql://prod-db-host:3306/momentum_prod?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#     username: prod_user
#     password: ${DB_PASSWORD} # 强烈建议从环境变量或配置中心读取敏感信息

# 生产环境建议关闭部分不必要的 Actuator 端点
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus # 只暴露健康检查和监控指标
