# ===================================================================
#                      开发环境配置 (Development Profile)
# ===================================================================

# 服务器端口配置
server:
  port: 8081
  servlet:
    context-path:

# Spring 核心配置
spring:
  # -------------------------------------------------------------------
  #                       数据库连接配置
  # -------------------------------------------------------------------
  datasource:
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接 URL
    # - jdbc:mysql://localhost:3306/momentum-suite: 连接到本地 3306 端口的 momentum-suite 数据库
    # - useUnicode=true&characterEncoding=utf8: 确保字符编码为 UTF-8，避免中文乱码
    # - serverTimezone=Asia/Shanghai: 设置服务器时区为上海，避免时间差问题
    url: jdbc:mysql://localhost:3306/momentum-suite?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: password
    # 连接池类型，Spring Boot 默认使用 HikariCP，性能非常出色
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池名称
      pool-name: MomentumSuiteHikariPool
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 最大生命周期（毫秒）
      max-lifetime: 1800000

# ===================================================================
#                       MyBatis-Plus 配置
# ===================================================================
mybatis-plus:
  # Mapper XML 文件的位置 (如果使用 XML 写 SQL)
  # classpath* 表示在所有类路径下查找
  mapper-locations: classpath*:/mapper/**/*.xml
  # POJO (持久化对象) 类别名扫描路径
  type-aliases-package: com.momentum.suite.infrastructure.persistent.po
  # 全局配置
  global-config:
    db-config:
      # 主键策略 (跟随POJO中的@TableId设置)
      id-type: assign_id
      # 表名前缀 (如果您的表都有统一前缀，例如 t_)
      table-prefix: t_
      logic-delete-field: delFlag # 全局指定逻辑删除字段名 (Java属性名)
      logic-delete-value: true    # 逻辑删除后的值 (1)
      logic-not-delete-value: false # 未删除的值 (0)
  # 配置
  configuration:
    # 开启驼峰命名转换：将数据库的 a_column 自动映射到 Java 的 aColumn
    map-underscore-to-camel-case: true
    # 在控制台打印执行的 SQL，方便开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    # 将 Mapper 接口的日志级别设为 DEBUG，可以看到更详细的 SQL 执行信息
    com.momentum.suite.infrastructure.persistent.mapper: debug
